var talkThroughs = [
  {
    name:"My recording",
data:[
  [
    "<!DOCTYPE html>",
    "<html>",
    "  <head>",
    "    <title>Webpage</title>",
    "    <meta charset=\"UTF-8\">",
    "  </head>",
    "  <body>",
    "    ",
    "  </body>",
    "</html>",
  ],
  [
    "<!DOCTYPE html>",
    "<html>",
    "  <head>",
    "    <title>Webpage</title>",
    "    <meta charset=\"UTF-8\">",
    "  </head>",
    "  <body>",
    "    HE",
    "  </body>",
    "</html>",
  ],
  [
    "<!DOCTYPE html>",
    "<html>",
    "  <head>",
    "    <title>Webpage</title>",
    "    <meta charset=\"UTF-8\">",
    "  </head>",
    "  <body>",
    "    HELLO",
    "  </body>",
    "</html>",
  ],
  [
    "<!DOCTYPE html>",
    "<html>",
    "  <head>",
    "    <title>Webpage</title>",
    "    <meta charset=\"UTF-8\">",
    "  </head>",
    "  <body>",
    "    HELLO wo",
    "  </body>",
    "</html>",
  ],
  [
    "<!DOCTYPE html>",
    "<html>",
    "  <head>",
    "    <title>Webpage</title>",
    "    <meta charset=\"UTF-8\">",
    "  </head>",
    "  <body>",
    "    HELLO world",
    "  </body>",
    "</html>",
  ],
  [
    "<!DOCTYPE html>",
    "<html>",
    "  <head>",
    "    <title>Webpage</title>",
    "    <meta charset=\"UTF-8\">",
    "  </head>",
    "  <body>",
    "HELLO world!!!!!",
    "  </body>",
    "</html>",
  ],
  [
    "<!DOCTYPE html>",
    "<html>",
    "  <head>",
    "    <title>Webpage</title>",
    "    <meta charset=\"UTF-8\">",
    "  </head>",
    "  <body>",
    "HELLO world!!!!!~!",
    "  </body>",
    "</html>",
  ],
  [
    "<!DOCTYPE html>",
    "<html>",
    "  <head>",
    "    <title>Webpage</title>",
    "    <meta charset=\"UTF-8\">",
    "  </head>",
    "  <body>",
    "HELLO world!!!!!~!",
    "  </body>",
    "</html>",
  ],
  [
    "<!DOCTYPE html>",
    "<html>",
    "  <head>",
    "    <title>Webpage</title>",
    "    <meta charset=\"UTF-8\">",
    "  </head>",
    "  <body>",
    "HELLO world!!!!!~!",
    "  </body>",
    "</html>",
  ],
  [
    "<!DOCTYPE html>",
    "<html>",
    "  <head>",
    "    <title>Webpage</title>",
    "    <meta charset=\"UTF-8\">",
    "  </head>",
    "  <body>",
    "HELLO world!!!!!~!",
    "  </body>",
    "</html>",
  ],
  [
    "<!DOCTYPE html>",
    "<html>",
    "  <head>",
    "    <title>Webpage</title>",
    "    <meta charset=\"UTF-8\">",
    "  </head>",
    "  <body>",
    "HELLO world!!!!!~!",
    "  </body>",
    "</html>",
  ],
],
cursor:[
  [7,4,],
  [7,6,],
  [7,9,],
  [7,12,],
  [7,15,],
  [7,16,],
  [7,18,],
  [7,18,],
  [7,18,],
  [7,18,],
  [7,18,],
],
    audioURL:"talk%20throughs/My%20Recording.ogg"
  },
  
]